%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
%!ignore_include 
nombre de groupes = 10
%Les commentaires doivent etre mis ici.
groupe = 1 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_debut
ech_temps = 1

%
groupe = 2 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_joystick
ech_temps = 1

%Les commentaires doivent etre mis ici.
groupe = 14 , type = 14 , nbre neurones = 10 , seuil = 0.000000
taillex = 1 , tailley = 10
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_joystick_buttons_to_neurons
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 15 , type = 29 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = RT
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 16 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_extract_neurons
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 17 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_send_command_to_serial
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 10 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_extract_neurons
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 11 , type = 14 , nbre neurones = 4 , seuil = 0.000000
taillex = 1 , tailley = 4
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_concatenation
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 12 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_extract_neurons
ech_temps = 0

%Les commentaires doivent etre mis ici.
groupe = 13 , type = 14 , nbre neurones = 1 , seuil = 0.000000
taillex = 1 , tailley = 1
learning rate = 1.000000 
simulation speed = 1.000000 
type2  = 0 
groupe = f_extract_neurons
ech_temps = 0

nombre de liaisons = 12
%Les commentaires doivent etre mis ici.
liaison entre 1   et 2 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = joy
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 15   et 14 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -B0-B1-B2-B3-B4-B5-B6-B7-B8-B9
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 2   et 15 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -t100000
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 14   et 16 , type = 5 , nbre = 10 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -M1-x0-y0
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 11   et 17 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -Narduino_outputs
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 14   et 10 , type = 5 , nbre = 10 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -M1-x0-y6
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 16   et 11 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = 0
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 10   et 11 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = 2
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 14   et 12 , type = 5 , nbre = 10 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -M-x0-y7
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 12   et 11 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = 3
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 14   et 13 , type = 5 , nbre = 10 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = -M-x0-y2
                         proba = 1.000000 
%Les commentaires doivent etre mis ici.
liaison entre 13   et 11 , type = 5 , nbre = 1 , norme = 0.100000
                         temps de memorisation entree= 0.000000 
                         temps de memorisation sortie= 0.000000 
                         mode de calcul        = 0 
                         secondaire            = 0 
                         nom = 1
                         proba = 1.000000 
